In [13]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model

In [14]:
np.random.seed(42)
tf.random.set_seed(42)

# Chuẩn bị dữ liệu

Ta sử dụng dataset **Emotions dataset for NLP** ([Nguồn](https://www.kaggle.com/datasets/praveengovi/emotions-dataset-for-nlp)).
Dữ liệu đã được xử lý trước để thuận tiện cho việc xây mô hình.

In [15]:
df = pd.read_csv("../data/NLP.csv")
df.head()

                                                text     emotion
0  i feel rather funny ending with so many dupes ...         fun
1                     i feel surprised by the result    surprise
2                    i am officially feeling festive     neutral
3  i suddenly found myself standing before this w...    surprise
4  i look at the meager pile of food i purchased ...  enthusiasm

Để xây mô hình, ta cần gán các cảm xúc cần dự đoán cho một chỉ số `emotion id` như dưới đây:

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['emotion id'] = le.fit_transform(df['emotion'])
df.head(10)

                                                text     emotion  emotion id
0  i feel rather funny ending with so many dupes ...         fun           3
1                     i feel surprised by the result    surprise          10
2                    i am officially feeling festive     neutral           7
3  i suddenly found myself standing before this w...    surprise          10
4  i look at the meager pile of food i purchased ...  enthusiasm           2
5  I, for one, am thrilled that Christ works outs...   happiness           4
6  i hate that she has the power to make me feel ...        hate           5
7                            i feel like i missed it     neutral           7
8  i have personally experienced this gut wrenchi...     sadness           9
9  i hate feeling that people see me as ugly but ...        hate           5

Ta xáo trộn dữ liệu trước khi tách để giúp tách tập dữ liệu cân đối hơn.

In [17]:
df = df.sample(frac=1).reset_index(drop=True)
df.head(10)

                                                text     emotion  emotion id
0  i respectfully call upon my friend and fellow ...     neutral           7
1  i normally have this i thought i was supposed ...         fun           3
2  the video on myspace is so funny...u run a lot...         fun           3
3  i got out from the hot shower feeling invigora...  enthusiasm           2
4  i feel reassured that god is real and has a se...     neutral           7
5  Slept through my first class -__- then bio all...   happiness           4
6  i feel empty and like i am living very much li...       empty           1
7  i just cant help but feel a tang of disappoint...         fun           3
8  i think i enjoy feeling long suffering and per...   happiness           4
9  i feel the empty space of what could have been...       empty           1

Tiến hành chia tập dữ liệu:

- Dữ liệu chia thành hai tập `raw` và `test` với tỉ lệ 8:2,
- Sau đó, chia tập `raw` thành `train` và `val` với tỉ lệ 7:1.

Như vậy, tỉ lệ chia dữ liệu là `train`:`val`:`test` = 7:1:2.

In [18]:
from sklearn.model_selection import train_test_split

X = df['text'].values
y = df['emotion id'].values

X_raw, X_test, y_raw, y_test = train_test_split(X,y,
                                                   test_size = 0.2,
                                                   random_state = 42)
X_raw = np.array(X_raw)
X_test = np.array(X_test)
y_raw = np.array(y_raw)
y_test = np.array(y_test)

X_train, X_val, y_train, y_val = train_test_split(X_raw, y_raw,
                                                 test_size=0.125,
                                                 random_state=42)

X_train = np.array(X_train)
X_val = np.array(X_val)
y_train = np.array(y_train)
y_val = np.array(y_val)

X_train.shape, X_val.shape, X_test.shape

((74448,), (10636,), (21271,))

# Xây dựng mô hình

Ta sử dụng tokenizer trước để xử lý các từ/cụm từ/kí tự đặc biệt thành số mà máy tính có thể hiểu được. Đây là quá trình **tokenize**

In [19]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

vocab_size = 10000
max_length = 150

tokenizer = Tokenizer(num_words = vocab_size, oov_token = "OOV") #out of vocabulary
tokenizer.fit_on_texts(X_train)

X_train_seqs = tokenizer.texts_to_sequences(X_train)
X_train_padded = pad_sequences(X_train_seqs, maxlen=max_length, padding="post")

X_val_seqs = tokenizer.texts_to_sequences(X_val)
X_val_padded = pad_sequences(X_val_seqs, maxlen=max_length, padding="post")

len(X_train_padded),len(X_val_padded)

(74448, 10636)

Bây giờ, ta sẽ tiến hành xây mô hình NLP.

In [20]:
num_classes = len(le.classes_)

embedding_dim = 64

model = keras.Sequential([
    keras.Input(shape=(max_length,)),
    keras.layers.Embedding(vocab_size, embedding_dim, trainable=True),
    keras.layers.Flatten(),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(num_classes, activation='softmax'),
])

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy']
)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 150, 64)        │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 9600)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 9600)           │        38,400 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       614,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           715 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,293,579 (4.93 MB)

 Trainable params: 1,274,379 (4.86 MB)

 Non-trainable params: 19,200 (75.00 KB)

# Huấn luyện mô hình

Ta bắt đầu huấn luyện mô hình với dữ liệu train và val đã xử lý ở trên.

In [12]:
from tensorflow.keras.callbacks import ModelCheckpoint

checkpoint = ModelCheckpoint(
    filepath = "NLP_ep{epoch:02d}.h5",
    save_weights_only = False,
    save_best_only = False,
    monitor = "val_loss",
    verbose = 1
)

history = model.fit(
    X_train_padded, y_train,
    validation_data = (X_val_padded, y_val),
    epochs = 15,
    callbacks = [checkpoint],
)

Epoch 1/15
2327/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3762 - loss: 1.7998
Epoch 1: saving model to NLP_ep01.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 35s 13ms/step - accuracy: 0.5588 - loss: 1.3296 - val_accuracy: 0.8052 - val_loss: 0.6574
Epoch 2/15
2327/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7557 - loss: 0.7690
Epoch 2: saving model to NLP_ep02.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 34s 15ms/step - accuracy: 0.7699 - loss: 0.7185 - val_accuracy: 0.8192 - val_loss: 0.6004
Epoch 3/15
2325/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8007 - loss: 0.6147
Epoch 3: saving model to NLP_ep03.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 35s 15ms/step - accuracy: 0.8053 - loss: 0.5932 - val_accuracy: 0.8298 - val_loss: 0.6001
Epoch 4/15
2326/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8245 - loss: 0.5313
Epoch 4: saving model to NLP_ep04.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 32s 14ms/step - accuracy: 0.8298 - loss: 0.5104 - val_accuracy: 0.8284 - val_loss: 0.6660
Epoch 5/15
2324/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8421 - loss: 0.4741
Epoch 5: saving model to NLP_ep05.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 33s 14ms/step - accuracy: 0.8483 - loss: 0.4560 - val_accuracy: 0.8313 - val_loss: 0.6719
Epoch 6/15
2323/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8562 - loss: 0.4230
Epoch 6: saving model to NLP_ep06.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 43s 18ms/step - accuracy: 0.8589 - loss: 0.4128 - val_accuracy: 0.8310 - val_loss: 0.6944
Epoch 7/15
2325/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8715 - loss: 0.3794
Epoch 7: saving model to NLP_ep07.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 33s 14ms/step - accuracy: 0.8727 - loss: 0.3713 - val_accuracy: 0.8332 - val_loss: 0.7838
Epoch 8/15
2324/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8787 - loss: 0.3610
Epoch 8: saving model to NLP_ep08.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 37s 16ms/step - accuracy: 0.8834 - loss: 0.3454 - val_accuracy: 0.8290 - val_loss: 0.8270
Epoch 9/15
2326/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8853 - loss: 0.3367
Epoch 9: saving model to NLP_ep09.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 38s 16ms/step - accuracy: 0.8903 - loss: 0.3229 - val_accuracy: 0.8322 - val_loss: 0.8187
Epoch 10/15
2327/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8934 - loss: 0.3125
Epoch 10: saving model to NLP_ep10.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 43s 17ms/step - accuracy: 0.8972 - loss: 0.2995 - val_accuracy: 0.8329 - val_loss: 0.8750
Epoch 11/15
2326/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9008 - loss: 0.2856
Epoch 11: saving model to NLP_ep11.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 35s 15ms/step - accuracy: 0.9035 - loss: 0.2793 - val_accuracy: 0.8311 - val_loss: 0.9715
Epoch 12/15
2326/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9092 - loss: 0.2679
Epoch 12: saving model to NLP_ep12.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 34s 15ms/step - accuracy: 0.9116 - loss: 0.2619 - val_accuracy: 0.8308 - val_loss: 1.0691
Epoch 13/15
2327/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9120 - loss: 0.2553
Epoch 13: saving model to NLP_ep13.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 38s 14ms/step - accuracy: 0.9148 - loss: 0.2485 - val_accuracy: 0.8286 - val_loss: 1.0947
Epoch 14/15
2327/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9157 - loss: 0.2481
Epoch 14: saving model to NLP_ep14.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 34s 15ms/step - accuracy: 0.9193 - loss: 0.2370 - val_accuracy: 0.8294 - val_loss: 1.0417
Epoch 15/15
2324/2327 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9222 - loss: 0.2300
Epoch 15: saving model to NLP_ep15.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

2327/2327 ━━━━━━━━━━━━━━━━━━━━ 31s 13ms/step - accuracy: 0.9243 - loss: 0.2247 - val_accuracy: 0.8288 - val_loss: 1.2455

# Kiểm tra mô hình

Bây giờ, ta kiểm tra độ chính xác của mô hình bằng cách kiểm tra.

In [21]:
X_test_seqs = tokenizer.texts_to_sequences(X_test)
X_test_padded = pad_sequences(X_test_seqs, padding='post', truncating='post', maxlen=max_length)

In [22]:
from tensorflow.keras.models import load_model

model = load_model("NLP_ep15.h5")
preds = model.predict(X_test_padded)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

665/665 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

# Đánh giá mô hình

Ta tiến hành đánh giá mô hình trên bằng các chỉ số:

- `accuracy`: độ chính xác của mô hình.
- `f1-score`: chỉ số đánh giá mô hình bằng cách kết hợp Precision (độ chính xác) và Recall (độ bao phủ). Nó được tính bằng trung bình điều hòa của hai giá trị này:

In [25]:
import numpy as np
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

pred_classes = np.argmax(preds, axis=1)

# Calculate individual metrics
accuracy = accuracy_score(y_test, pred_classes)
precision = precision_score(y_test, pred_classes, average='weighted')
recall = recall_score(y_test, pred_classes, average='weighted')
f1 = f1_score(y_test, pred_classes, average='weighted')

print(f"Accuracy:  {accuracy * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall:    {recall * 100:.2f}%")
print(f"F1-Score:  {f1 * 100:.2f}%\n")

print("Classification Report:")
print(classification_report(y_test, pred_classes))

Accuracy:  82.40%
Precision: 83.05%
Recall:    82.40%
F1-Score:  82.56%

Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.85      0.80      2066
           1       0.93      0.87      0.90      1246
           2       0.93      0.91      0.92      2029
           3       0.92      0.85      0.89      1994
           4       0.64      0.74      0.69      2027
           5       0.96      0.91      0.93      2012
           6       0.91      0.90      0.91      2014
           7       0.81      0.84      0.82      1937
           8       0.90      0.90      0.90      1997
           9       0.60      0.64      0.62      1956
          10       0.81      0.66      0.73      1993

    accuracy                           0.82     21271
   macro avg       0.83      0.83      0.83     21271
weighted avg       0.83      0.82      0.83     21271